import { NextResponse } from "next/server";

export async function POST() {
  try {
    // Dummy data for properties
    const dummyData = {
      status: "success",
      response_data: {
        properties: {
          completed: [
            {
              id: 1,
              property_name: "Rio Estado Villa",
              location: "Goa, India",
              price: "₹2.5 Cr",
              main_image: "/homepage_images/rio-estado-master-bedroom_web.webp",
              description: "Luxury villa with modern amenities",
              bedrooms: 3,
              bathrooms: 2,
              area: "2500 sq ft",
              property_url: "/properties/rio-estado-villa/",
              development_status: "completed",
              configuration: "3 BHK",
              is_sold_out: "n",
            },
            {
              id: 2,
              property_name: "Rio Casa Rumah",
              location: "Goa, India",
              price: "₹3.2 Cr",
              main_image: "/homepage_images/home_casa_rumah.webp",
              description: "Premium villa with pool and garden",
              bedrooms: 4,
              bathrooms: 3,
              area: "3200 sq ft",
              property_url: "/properties/casa-rumah/",
              development_status: "completed",
              configuration: "4 BHK",
              is_sold_out: "n",
            },
          ],
          ongoing: [
            {
              id: 3,
              property_name: "Rio Black Forest",
              location: "Goa, India",
              price: "₹4.1 Cr",
              main_image: "/homepage_images/black_forest_image.webp",
              description: "Exclusive villa in forest setting",
              bedrooms: 5,
              bathrooms: 4,
              area: "4500 sq ft",
              property_url: "/properties/black-forest/",
              development_status: "ongoing",
              configuration: "5 BHK",
              is_sold_out: "n",
            },
          ],
          upcoming: [
            {
              id: 4,
              property_name: "Rio Phuket Resort",
              location: "Phuket, Thailand",
              price: "₹5.8 Cr",
              main_image: "/homepage_images/phuket_image.webp",
              description: "Beachfront luxury resort",
              bedrooms: 6,
              bathrooms: 5,
              area: "6000 sq ft",
              property_url: "/properties/phuket-resort/",
              development_status: "upcoming",
              configuration: "6 BHK",
              is_sold_out: "n",
            },
            {
              id: 5,
              property_name: "The Village",
              location: "Goa, India",
              price: "₹3.8 Cr",
              main_image: "/homepage_images/rio-estado-master-bedroom_web.webp",
              description: "Premium residential development",
              bedrooms: 4,
              bathrooms: 3,
              area: "3200 sq ft",
              property_url: "/properties/the-village/",
              development_status: "upcoming",
              configuration: "4 BHK",
              is_sold_out: "n",
            },
          ],
          all_properties: [
            {
              id: 1,
              property_name: "Rio Estado Villa",
              location: "Goa, India",
              price: "₹2.5 Cr",
              main_image: "/homepage_images/rio-estado-master-bedroom_web.webp",
              description: "Luxury villa with modern amenities",
              bedrooms: 3,
              bathrooms: 2,
              area: "2500 sq ft",
              property_url: "/properties/rio-estado-villa/",
              development_status: "completed",
              configuration: "3 BHK",
              is_sold_out: "n",
            },
            {
              id: 2,
              property_name: "Rio Casa Rumah",
              location: "Goa, India",
              price: "₹3.2 Cr",
              main_image: "/homepage_images/home_casa_rumah.webp",
              description: "Premium villa with pool and garden",
              bedrooms: 4,
              bathrooms: 3,
              area: "3200 sq ft",
              property_url: "/properties/casa-rumah/",
              development_status: "completed",
              configuration: "4 BHK",
              is_sold_out: "n",
            },
            {
              id: 3,
              property_name: "Rio Black Forest",
              location: "Goa, India",
              price: "₹4.1 Cr",
              main_image: "/homepage_images/black_forest_image.webp",
              description: "Exclusive villa in forest setting",
              bedrooms: 5,
              bathrooms: 4,
              area: "4500 sq ft",
              property_url: "/properties/black-forest/",
              development_status: "ongoing",
              configuration: "5 BHK",
              is_sold_out: "n",
            },
            {
              id: 4,
              property_name: "Rio Phuket Resort",
              location: "Phuket, Thailand",
              price: "₹5.8 Cr",
              main_image: "/homepage_images/phuket_image.webp",
              description: "Beachfront luxury resort",
              bedrooms: 6,
              bathrooms: 5,
              area: "6000 sq ft",
              property_url: "/properties/phuket-resort/",
              development_status: "upcoming",
              configuration: "6 BHK",
              is_sold_out: "n",
            },
            {
              id: 5,
              property_name: "The Village",
              location: "Goa, India",
              price: "₹3.8 Cr",
              main_image: "/homepage_images/rio-estado-master-bedroom_web.webp",
              description: "Premium residential development",
              bedrooms: 4,
              bathrooms: 3,
              area: "3200 sq ft",
              property_url: "/properties/the-village/",
              development_status: "upcoming",
              configuration: "4 BHK",
              is_sold_out: "n",
            },
          ],
        },
        blog_posts: [
          {
            id: 1,
            post_title: "Luxury Living in Goa",
            post_content:
              "Discover the beauty of luxury living in Goa with RIO Luxury Homes. Experience modern amenities and natural beauty in our premium properties.",
            post_image_name: "/properties_image/blog1.webp",
            post_url: "/blog/luxury-living-goa",
            date: "2024-01-15",
          },
          {
            id: 2,
            post_title: "Investment Opportunities",
            post_content:
              "Explore high-ROI investment opportunities in Goa's luxury real estate market. RIO Luxury Homes offers excellent returns and premium locations.",
            post_image_name: "/properties_image/blog2.webp",
            post_url: "/blog/investment-opportunities",
            date: "2024-01-10",
          },
          {
            id: 3,
            post_title: "Modern Architecture Trends",
            post_content:
              "Latest trends in luxury villa architecture and design. Discover how RIO Luxury Homes incorporates modern design principles.",
            post_image_name: "/properties_image/blog1.webp",
            post_url: "/blog/modern-architecture-trends",
            date: "2024-01-05",
          },
        ],
      },
    };

    return NextResponse.json(dummyData);
  } catch {
    return NextResponse.json(
      { status: "error", message: "Internal server error" },
      { status: 500 }
    );
  }
}
